---
- name: Setup demo
  hosts: localhost
  connection: local
  tasks:
    - name: Create Checkpoint Firewall template
      tower_job_template:
        name: "Create Checkpoint Access Rule"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Security Demo"
        playbook: "checkpoint.yml"
        credential: "Workshop Credential"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'files/checkpoint_survey.json') }}"