---
- name: Basic server compliance
  hosts: all
  vars:
    allowed_ssh_networks:
      - 172.16.249.0/24
      - 172.16.252.0/24
    unnecessary_software:
      - tcpdump 
      - nmap-ncat 
      - wpa_supplicant 
    unnecessary_services:
      - postfix 
      - telnet 
  tasks:
    - name: Perform full patching 
      package:
        name: '*'
        state: latest 
      tags:
        - patch 
        - never
      
    - name: Secure remote access
      block:
        - name: Add admin group
          group:
            name: admin
            state: present 

        - name: Add local user
          user:
            name: admin
            group: admin
            shell: /bin/bash 
            home: /home/admin 
            create_home: yes 
            state: present 

        - name: Add SSH public key for user
          authorized_key:
            user: admin
            key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
            state: present 

        - name: Add sudoer rule for local user
          copy:
            dest: /etc/sudoers.d/admin 
            src: etc/sudoers.d/admin 
            owner: root
            group: root 
            mode: 0440 
            validate: /usr/sbin/visudo -csf %s 

      tags:
        - admin 
        - never

    - name: Harden SSH Config
      copy:
        dest: /etc/ssh/sshd_config
        src: etc/ssh/sshd_config 
        owner: root
        group: root
        mode: 0600 
      notify: Reload SSH 
      tags:
        - ssh 
        - never 

    # - name: Configure firewalld 
    #   block:
    #     - name: Add SSH port to internal zone
    #       zone: internal
    #       service: ssh 
    #       state: enabled 
    #       immediate: yes 
    #       permanent: yes 

    #     - name: Add permitted networks to internal zone
    #       firewalld:
    #         zone: internal 
    #         source: "{{ item }}"
    #         state: enabled
    #         immediate: yes
    #         permanent: yes 
    #       loop: "{{ allowed_ssh_networks }}"

    #     - name: Drop SSH from the public zone
    #       firewalld:
    #         zone: public
    #         service: ssh
    #         state: disabled
    #         immediate: yes
    #         permanent: yes 
    #   tags:
    #     - firewall 
    #     - never 

    - name: Disable unused software and services
      block:
        - name: remove undesirable packages
          package:
            name: "{{ unnecessary_software }}"
            state: absent 

        - name: Stop and disable unnecessary services
          service:
            name: "{{ item }}"
            state: stopped 
            enabled: no
          loop: "{{ unnecessary_services }}"
          ignore_errors: yes
      tags:
        - never 
        - unused 

    - name: Security Policy Improvements
      block:
        - name: set a message of the day
          copy:
            dest: /etc/motd 
            src: etc/motd 
            owner: root 
            group: root 
            mode: 0644 
        
        - name: Set a login banner 
          copy:
            dest: "{{ item }}"
            src: etc/issue 
            owner: root 
            group: root 
            mode: 0644 
          loop:
            - /etc/issue 
            - /etc/issue.net 
  handlers:
    - name: Reload SSH  
      service:
        name: sshd 
        state: reloaded 

  